version: '3.5'

services:
  api_devops:
    container_name: api_devops
    image: django_devops
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 80:8000
    depends_on:
      - tasks-migrate
      - mongo
    networks:
      - django_devops_network

  tasks-migrate:
    container_name: migrate
    image: django_devops
    build:
      context: .
    command: python manage.py migrate
    volumes:
      - .:/code
    networks:
      - django_devops_network
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: django_devops
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: '123456'
    networks:
      - django_devops_network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      MONGO_INITDB_DATABASE: django_devops
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: '123456'
    networks:
      - django_devops_network

networks:
  django_devops_network:
    name: djangodevopsnetwork
    ipam:
      config:
        - subnet: 172.21.0.0/16