---
- name: Configurations to "remote" host
  hosts: remote
  remote_user: root
  become: yes
  pre_tasks:
    - name: Apt update
      raw: sudo apt -y update

  tasks:
    - name: Setup machine
      import_role:
        name: setup
      become: yes
    
    - name: Config and install application
      import_role:
        name: application
      become: yes